(function(){
  const IMG={
    carros:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=86',
    motos:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1600&q=86',
    bikes:'https://images.unsplash.com/photo-1529422643029-d4585747aaf2?auto=format&fit=crop&w=1600&q=86',
    eletricos:'https://images.unsplash.com/photo-1592833159155-c62df1b65634?auto=format&fit=crop&w=1600&q=86',
    locadoras:'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1600&q=86',
    concessionarias:'https://images.unsplash.com/photo-1562141961-b5d1be7b0a25?auto=format&fit=crop&w=1600&q=86',
    nautica:'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1600&q=86',
    aviacao:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=86',
    tecnologia:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=86',
    entrevista:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=86'
  };
  const articles={};
  function add(id,theme,kicker,title,summary,image,body,extra={}){articles[id]={id,theme,kicker,title,summary,image,body,...extra};return id}

  add('lancamento-jeep-avenger-2026','lancamentos','LANÇAMENTO • 02 SET 2026','Jeep Avenger chega oficialmente ao mercado brasileiro e abre nova disputa entre SUVs compactos híbridos','O novo SUV compacto da Jeep estreia no Brasil com sistema híbrido leve, três versões e pacote tecnológico voltado ao uso urbano.',IMG.carros,[
    'O Jeep Avenger passa a integrar oficialmente o mercado brasileiro em setembro de 2026. A chegada amplia a presença da marca no segmento de SUVs compactos e coloca o modelo diante de uma disputa cada vez mais concentrada em tecnologia, eficiência e conectividade.',
    'Segundo informações divulgadas pela Jeep, o modelo é oferecido nas versões Altitude, Longitude e Limited, todas com transmissão automática e sistema híbrido leve MHEV de 12V associado ao motor turbo T200.',
    'A proposta combina dimensões urbanas com posição de dirigir elevada. Entre os destaques anunciados estão pacote ADAS de nível 2, painel digital, central multimídia e recursos conectados. Para o consumidor, o ponto central será comparar preço, consumo, segurança, espaço interno e custo total de uso com os rivais diretos.',
    'Em 2 de setembro, a marca apresentou uma nova campanha nacional para marcar a chegada do Avenger ao mercado. O VOZ NEWS Mobilidade acompanhará os próximos passos do modelo, incluindo disponibilidade, rede, versões e comportamento de mercado.'
  ],{date:'02 de setembro de 2026',source:'Jeep / Stellantis Media',sourceUrl:'https://www.media.stellantis.com/br-pt/jeep/press/novo-jeep-avenger-encara-uma-serie-de-desafios-inspirados-nos-viloes-da-marvel-em-uma-campanha-criada-para-marcar-o-lancamento-do-novo-modelo'});

  add('automoveis-mercado','automoveis','MERCADO AUTOMOTIVO','O que realmente pesa na escolha de um carro novo em 2026','Preço de compra é apenas uma parte da decisão: tecnologia, seguro, consumo, manutenção e revenda formam o custo real.',IMG.carros,['A compra de um automóvel passou a exigir uma leitura mais ampla do que apenas potência e preço de tabela.','Eficiência, disponibilidade de peças, seguro, pacote de segurança, conectividade e valor de revenda podem alterar completamente o custo total de propriedade.','O VOZ NEWS Mobilidade organiza esses fatores para facilitar a comparação entre categorias e propostas de uso.']);
  add('automoveis-seguranca','automoveis','SEGURANÇA','ADAS deixa de ser sigla distante e entra na decisão de compra','Frenagem autônoma, alerta de faixa e controle de cruzeiro adaptativo passam a diferenciar versões e segmentos.',IMG.carros,['Sistemas avançados de assistência ao motorista ganharam espaço em veículos de diferentes faixas de preço.','Mais importante do que a quantidade de recursos é entender como eles funcionam, quais são de série e quais dependem de pacotes opcionais.','A cobertura da editoria compara tecnologia disponível com uso real, sem transformar ficha técnica em propaganda.']);
  add('automoveis-test-drive','automoveis','TEST-DRIVE','Ficha técnica não conta tudo: o que observar ao dirigir antes de comprar','Ergonomia, visibilidade, ruído, resposta do câmbio e conforto aparecem de verdade quando o carro sai do showroom.',IMG.carros,['Um bom test-drive precisa reproduzir parte do cotidiano do comprador.','Trânsito, manobras, frenagens, ruas irregulares e pequenos trechos de velocidade constante mostram características que não aparecem na ficha técnica.','A avaliação deve considerar também acesso ao banco traseiro, porta-malas, comandos e facilidade de uso da central multimídia.']);

  add('motos-mercado','motos','DUAS RODAS','Scooters, urbanas, trails e premium atendem rotinas completamente diferentes','Antes de comparar cilindrada, é preciso entender deslocamento, ergonomia, custo de uso e perfil do motociclista.',IMG.motos,['O mercado de motos reúne produtos com propostas muito diferentes.','Uso profissional, deslocamento urbano, viagens e lazer exigem ergonomia, autonomia e equipamentos distintos.','Escolher categoria antes de escolher modelo reduz a chance de comprar mais — ou menos — motocicleta do que o necessário.']);
  add('motos-seguranca','motos','SEGURANÇA','ABS, controle de tração e iluminação: tecnologia que faz diferença em duas rodas','Equipamentos eletrônicos se tornam parte central da evolução das motocicletas.',IMG.motos,['Segurança ativa evoluiu rapidamente nas motocicletas.','ABS, controle de tração e diferentes modos de condução precisam ser avaliados junto com pneus, posição de pilotagem e qualidade da iluminação.','Tecnologia ajuda, mas não substitui equipamento adequado, treinamento e condução defensiva.']);
  add('motos-estrada','motos','VIAGEM','Como preparar moto e piloto para pegar estrada','Autonomia, bagagem, proteção aerodinâmica e manutenção definem a qualidade de uma viagem longa.',IMG.motos,['Viajar de moto exige planejamento diferente do automóvel.','Intervalos, combustível, condição dos pneus, previsão do tempo e capacidade de bagagem influenciam conforto e segurança.','A escolha de acessórios deve priorizar funcionalidade e estabilidade.']);

  add('bikes-cidade','bikes','MOBILIDADE URBANA','Bicicleta ganha espaço quando a cidade conecta trajetos seguros','Ciclovias isoladas ajudam menos do que redes contínuas ligadas ao transporte e aos destinos cotidianos.',IMG.bikes,['A bicicleta é eficiente em deslocamentos curtos e médios, mas sua adoção depende de infraestrutura.','Conexões seguras, bicicletários e integração com transporte coletivo aumentam a utilidade do modal.','A mobilidade ativa também reduz pressão sobre estacionamentos e pequenos deslocamentos motorizados.']);
  add('bikes-eletricas','bikes','E-BIKES','E-bike transforma distância e relevo na mobilidade de curta distância','Assistência elétrica amplia o público e torna trajetos antes difíceis mais acessíveis.',IMG.bikes,['Motores compactos e baterias mais eficientes ampliaram o uso das bicicletas elétricas.','A escolha deve considerar autonomia real, assistência, peso, disponibilidade de manutenção e segurança da bateria.','Em muitos trajetos urbanos, a e-bike ocupa um espaço entre bicicleta convencional, transporte público e automóvel.']);
  add('bikes-turismo','bikes','TURISMO','Cicloturismo une deslocamento, experiência e economia local','Rotas bem estruturadas transformam bicicleta em produto turístico.',IMG.bikes,['Cicloturismo movimenta hospedagem, gastronomia, oficinas e serviços de apoio.','Sinalização, pontos de descanso e informação confiável são essenciais para a experiência.','Destinos que tratam a bicicleta como infraestrutura turística ampliam permanência e circulação de visitantes.']);

  add('eletricos-mercado','eletricos','ELETRIFICAÇÃO','Elétricos e híbridos deixam de ser nicho isolado e passam a disputar segmentos tradicionais','A comparação agora envolve arquitetura elétrica, autonomia, eficiência e rede de atendimento.',IMG.eletricos,['A eletrificação avança em diferentes formatos: híbrido leve, híbrido convencional, plug-in e elétrico a bateria.','Cada tecnologia atende perfis de uso distintos e não deve ser comparada apenas pelo consumo declarado.','Preço, recarga, garantia da bateria e valor residual entram na conta.']);
  add('eletricos-recarga','eletricos','RECARGA','Onde carregar é tão importante quanto a autonomia declarada','Casa, condomínio, trabalho e corredores rodoviários formam a infraestrutura real de quem usa um elétrico.',IMG.eletricos,['Autonomia de catálogo não resolve sozinha a rotina do proprietário.','A experiência depende da disponibilidade de recarga onde o veículo permanece parado e nos trajetos mais longos.','Potência do carregador, curva de recarga e compatibilidade do veículo determinam o tempo necessário.']);
  add('eletricos-custo','eletricos','CUSTO TOTAL','Energia barata não encerra a conta do carro elétrico','Seguro, pneus, depreciação, manutenção e recarga pública devem entrar no cálculo.',IMG.eletricos,['O custo por quilômetro de energia pode ser competitivo, mas a análise precisa ser completa.','Perfil de uso, quilometragem anual, preço de aquisição e depreciação alteram a vantagem econômica.','A comparação correta deve usar o mesmo período e condições de uso entre tecnologias.']);

  add('locadoras-redes','locadoras','LOCAÇÃO','Grandes redes ampliam a locação para turismo, empresas e uso cotidiano','Localiza, Movida, Unidas e redes internacionais disputam um consumidor cada vez mais digital.',IMG.locadoras,['A locação deixou de ser associada apenas a viagens.','Frotas corporativas, carros por assinatura, substituição temporária e demandas sazonais ampliaram o mercado.','Preço final deve ser comparado com proteções, franquias, quilometragem, combustível e regras de retirada.']);
  add('locadoras-aeroportos','locadoras','AEROPORTOS','Retirar carro no aeroporto é conveniente, mas exige comparação completa','Horário, fila, traslado, taxas e devolução precisam entrar na escolha.',IMG.locadoras,['Aeroportos concentram grande oferta de locadoras e diferentes modelos de retirada.','Nem sempre a menor tarifa inicial representa o menor preço final.','Antes de reservar, vale conferir política de combustível, adicionais, horário de devolução e distância do balcão até o veículo.']);
  add('locadoras-assinatura','locadoras','ASSINATURA','Carro por assinatura transforma propriedade em serviço mensal','Previsibilidade atrai consumidores que preferem concentrar custos em uma mensalidade.',IMG.locadoras,['Planos de assinatura combinam uso do veículo com manutenção, documentação e outros custos definidos em contrato.','A comparação deve considerar quilometragem, prazo, multas de saída e itens incluídos.','Para alguns perfis a previsibilidade compensa; para outros, compra ou locação eventual pode ser mais econômica.']);

  add('concessionarias-digital','concessionarias','VAREJO','Concessionária física e jornada digital precisam funcionar como uma só experiência','O cliente pesquisa online, conversa por mensagem, visita a loja e espera continuidade.',IMG.concessionarias,['A jornada de compra ficou híbrida.','Preço, estoque e agendamento precisam estar alinhados entre site, atendimento remoto e loja.','Quando o consumidor precisa recomeçar a negociação em cada canal, a experiência perde valor.']);
  add('concessionarias-posvenda','concessionarias','PÓS-VENDA','Oficina e peças influenciam a recompra tanto quanto o showroom','Relacionamento após a venda define parte importante da reputação de uma rede.',IMG.concessionarias,['Prazo de revisão, transparência de orçamento e disponibilidade de peças pesam na fidelização.','O pós-venda é o contato mais frequente entre cliente e marca depois da compra.','Boa experiência reduz atrito e aumenta confiança na próxima troca.']);
  add('concessionarias-experiencia','concessionarias','EXPERIÊNCIA','Test-drive bem organizado virou ferramenta de venda e informação','O consumidor precisa experimentar o produto na situação mais próxima possível do seu uso.',IMG.concessionarias,['Test-drives curtos demais mostram pouco do veículo.','Roteiros com cidade, manobras e diferentes pisos ajudam o cliente a avaliar conforto e dirigibilidade.','A experiência também deve explicar tecnologia sem excesso de linguagem técnica.']);

  add('nautica-mercado','nautica','MERCADO NÁUTICO','Embarcação é apenas uma parte de uma cadeia que inclui marina, manutenção e serviços','O custo de uso precisa considerar guarda, combustível, seguro e manutenção.',IMG.nautica,['O mercado náutico envolve fabricantes, revendas, marinas, oficinas e serviços especializados.','A compra deve considerar região de navegação, capacidade, motorização e infraestrutura disponível.','Planejamento de uso evita que a embarcação fique incompatível com a rotina do proprietário.']);
  add('nautica-marinas','nautica','MARINAS','Marina é infraestrutura de mobilidade, turismo e lazer','Localização, segurança e serviços de apoio alteram a experiência sobre a água.',IMG.nautica,['Marinas organizam acesso, guarda e suporte às embarcações.','Serviços de abastecimento, manutenção e apoio ao usuário tornam o local parte da experiência.','Em destinos turísticos, a marina também conecta restaurantes, hospedagem e atividades náuticas.']);
  add('nautica-tecnologia','nautica','TECNOLOGIA A BORDO','Navegação, conectividade e segurança modernizam o uso das embarcações','Eletrônica embarcada melhora informação e controle, mas exige instalação e manutenção adequadas.',IMG.nautica,['Sistemas de navegação e monitoramento ficaram mais acessíveis.','Integração entre instrumentos ajuda o comandante a acompanhar rota, profundidade e funcionamento de sistemas.','Tecnologia precisa ser tratada como apoio, não substituto de planejamento e conhecimento de navegação.']);

  add('aviacao-companhias','aviacao','COMPANHIAS AÉREAS','Companhias aéreas competem por malha, frequência, preço e experiência do passageiro','Conectividade é resultado da combinação de rotas, horários, aeroportos e integração entre voos.',IMG.aviacao,['A escolha de uma companhia aérea vai além da tarifa.','Horários, conexões, política de bagagem, pontualidade e suporte em irregularidades moldam a experiência.','No mercado corporativo, frequência e flexibilidade podem valer mais do que a menor tarifa disponível.']);
  add('aviacao-taxi-aereo','aviacao','TÁXI AÉREO','Táxi aéreo atende missões em que tempo, acesso e flexibilidade são decisivos','Operações sob demanda conectam cidades e aeroportos que nem sempre possuem voos regulares adequados.',IMG.aviacao,['Táxi aéreo atende deslocamentos executivos, operações especiais e regiões com baixa oferta regular.','A contratação deve observar operador autorizado, aeronave adequada, condições da missão e estrutura aeroportuária.','Tempo total de viagem e acesso ao destino são os principais diferenciais desse tipo de operação.']);
  add('aviacao-aeroportos','aviacao','AEROPORTOS','Aeroporto eficiente conecta pista, terminal, acesso terrestre e serviços','A experiência começa antes do embarque e termina depois da retirada da bagagem.',IMG.aviacao,['Infraestrutura aeroportuária influencia conectividade e qualidade da viagem.','Acesso viário, transporte público, estacionamento e processos de segurança fazem parte do sistema.','Para companhias, capacidade de pista, pátio e terminal condiciona expansão de rotas.']);
  add('aviacao-executiva','aviacao','AVIAÇÃO EXECUTIVA','Aviação executiva transforma tempo em ativo de mobilidade','Jatos, turbo-hélices e helicópteros atendem missões distintas e precisam ser dimensionados ao perfil de voo.',IMG.aviacao,['A aviação executiva combina flexibilidade de horário e acesso a uma rede maior de aeroportos.','Escolha de aeronave depende de distância, número de passageiros, pista disponível e bagagem.','Gestão, manutenção e segurança operacional são componentes centrais do serviço.']);

  add('tecnologia-conectada','tecnologia','CONECTIVIDADE','Veículo conectado transforma manutenção, navegação e serviços','Software passa a acompanhar o automóvel durante toda a vida útil.',IMG.tecnologia,['Telemetria e conectividade permitem novos serviços ao usuário e à operação de frotas.','Atualizações, diagnóstico remoto e integração com aplicativos aproximam veículo e plataforma digital.','A discussão também envolve privacidade, segurança de dados e vida útil do software.']);
  add('tecnologia-ia','tecnologia','INTELIGÊNCIA ARTIFICIAL','IA entra na mobilidade pela navegação, atendimento e assistência ao condutor','O valor está menos no rótulo e mais na capacidade de simplificar tarefas.',IMG.tecnologia,['Sistemas de IA aparecem em comandos de voz, planejamento de rotas e suporte ao usuário.','Para gerar valor, precisam reduzir etapas e oferecer respostas relevantes ao contexto de uso.','Transparência sobre limites e dados utilizados é parte da confiança na tecnologia.']);
  add('tecnologia-pagamentos','tecnologia','SERVIÇOS DIGITAIS','Pedágio, estacionamento e recarga caminham para uma experiência integrada','Pagamentos invisíveis reduzem atrito, mas exigem interoperabilidade entre sistemas.',IMG.tecnologia,['Mobilidade reúne uma série de pequenos pagamentos ao longo da viagem.','Integração entre aplicativos, veículos e infraestrutura pode simplificar esse processo.','O desafio é permitir escolha, segurança e clareza de cobrança.']);

  add('lancamentos-agenda','lancamentos','AGENDA DE NOVIDADES','Como o VOZ NEWS separa lançamento real de simples mudança de linha','Nova geração, novo modelo e atualização anual possuem impactos diferentes para o consumidor.',IMG.carros,['Nem toda novidade tem o mesmo peso.','Mudança de motorização, plataforma ou pacote de segurança costuma ter impacto maior do que alterações apenas visuais.','A editoria classifica as novidades pelo efeito prático na escolha e no mercado.']);
  add('lancamentos-analise','lancamentos','ANÁLISE','Preço de lançamento precisa ser lido junto com versão, equipamentos e concorrentes','Comparação justa exige olhar para a configuração efetivamente disponível.',IMG.carros,['Preço promocional de estreia pode ter prazo, lote ou condição específica.','A análise compara equipamentos de série, garantia e proposta dos concorrentes diretos.','O objetivo é mostrar posicionamento de mercado, não apenas repetir o valor divulgado.']);

  add('carros-escolha','carros','GUIA','SUV, sedã, hatch ou picape: comece pelo uso, não pela moda','Garagem, família, bagagem, estrada e rotina ajudam a definir o segmento correto.',IMG.carros,['Segmentos diferentes resolvem necessidades diferentes.','Dimensões externas, espaço interno e tipo de suspensão interferem mais no cotidiano do que muitos itens de marketing.','A escolha certa começa pelo uso mais frequente.']);
  add('carros-performance','carros','DESEMPENHO','Potência isolada não explica como um carro responde no uso real','Peso, torque, câmbio, pneus e calibração trabalham juntos.',IMG.carros,['Números de potência ajudam a comparar, mas não contam toda a experiência.','Resposta em baixa velocidade e comportamento do câmbio podem ser mais importantes na cidade.','Em estrada, retomadas, estabilidade e frenagem ganham peso.']);
  add('carros-tecnologia','carros','TECNOLOGIA','Central multimídia boa é a que exige menos atenção do motorista','Tamanho de tela não substitui ergonomia, rapidez e comandos bem organizados.',IMG.tecnologia,['A interface do veículo virou parte da experiência de direção.','Menus complexos podem aumentar distração mesmo em telas grandes.','Comandos físicos estratégicos e integração consistente ajudam no uso cotidiano.']);

  add('test-drive-metodo','test-drive','AVALIAÇÃO VOZ','Nosso roteiro de test-drive começa pela vida real','A avaliação considera acesso, ergonomia, cidade, estrada, consumo e facilidade de uso.',IMG.carros,['Testar um veículo exige método para evitar conclusões baseadas apenas na primeira impressão.','O VOZ NEWS organiza a avaliação em etapas comparáveis entre modelos.','O resultado destaca pontos fortes, limitações e perfil de usuário.']);
  add('test-drive-cidade','test-drive','CIDADE','Manobra, visibilidade e suavidade valem muito no uso urbano','O cotidiano revela qualidades que desaparecem em uma volta curta em pista lisa.',IMG.carros,['Ruas apertadas e estacionamento mostram dimensões e raio de giro.','Trânsito revela progressividade de acelerador, câmbio e freio.','Piso irregular ajuda a avaliar conforto e ruídos de acabamento.']);
  add('test-drive-estrada','test-drive','ESTRADA','Retomada, estabilidade e ruído definem parte da experiência rodoviária','Viagem longa expõe características diferentes das percebidas na cidade.',IMG.carros,['Na estrada, reserva de desempenho e estabilidade ganham importância.','Ruído aerodinâmico e conforto dos bancos pesam ao longo do tempo.','Consumo deve ser observado em condições comparáveis de velocidade e carga.']);

  add('entrevistas-executivos','entrevistas','ENTREVISTAS','Executivos explicam investimento, produto e estratégia diretamente à audiência','A editoria abre espaço para perguntas objetivas sobre decisões que afetam o mercado.',IMG.entrevista,['Entrevistas ajudam a contextualizar anúncios e investimentos.','O foco é transformar linguagem corporativa em informação útil para consumidores e empresas.','Compromissos e previsões podem ser acompanhados ao longo do tempo.']);
  add('entrevistas-especialistas','entrevistas','ESPECIALISTAS','Tecnologia complexa precisa de explicação clara','Engenheiros e especialistas ajudam a separar inovação concreta de terminologia de marketing.',IMG.entrevista,['Eletrificação, segurança e conectividade possuem conceitos técnicos que podem confundir.','A participação de especialistas amplia contexto e permite comparar soluções.','O objetivo é explicar sem simplificar demais.']);
  add('entrevistas-futuro','entrevistas','VISÃO DE FUTURO','Infraestrutura e regulação definem o ritmo da mobilidade','Produto e serviço dependem de estrada, energia, aeroportos, telecomunicações e regras.',IMG.entrevista,['Mobilidade é um sistema, não apenas uma coleção de veículos.','Políticas públicas e investimento privado se encontram em infraestrutura e serviços.','Entrevistas com diferentes atores ajudam a enxergar dependências e oportunidades.']);

  add('paulo-fayad-analise','paulo-fayad','COMENTÁRIO VOZ','Mobilidade é economia em movimento','Indústria, serviços, turismo e infraestrutura se encontram em cada deslocamento.',IMG.carros,['A mobilidade revela mudanças de comportamento e investimento.','Quando uma nova rota, veículo ou serviço surge, seu impacto alcança emprego, turismo, comércio e produtividade.','A cobertura precisa enxergar esse conjunto, não apenas o produto isolado.']);
  add('paulo-fayad-mercado','paulo-fayad','PAULO FAYAD','O consumidor mudou antes de muitas empresas perceberem','Pesquisa online, reputação e experiência passaram a influenciar decisões antes do primeiro contato presencial.',IMG.entrevista,['O processo de compra começa muito antes da loja.','Marcas que entregam informação clara e atendimento coerente tendem a reduzir atrito.','Comunicação e experiência precisam contar a mesma história.']);
  add('paulo-fayad-infra','paulo-fayad','INFRAESTRUTURA','Não existe mobilidade moderna sem integração entre modais','Estradas, aeroportos, energia e tecnologia precisam funcionar como rede.',IMG.aviacao,['Projetos isolados resolvem apenas parte do deslocamento.','A integração entre modais reduz tempo e aumenta eficiência econômica.','O desafio é planejar a jornada completa do usuário e da carga.']);

  add('deijanete-fayad-comportamento','deijanete-fayad','COMPORTAMENTO','Escolher como se mover também é escolher rotina e estilo de vida','Tempo, segurança percebida, conforto e previsibilidade influenciam decisões de mobilidade.',IMG.locadoras,['Decisões de mobilidade são profundamente ligadas à rotina.','Uma solução tecnicamente eficiente pode ser rejeitada se gerar insegurança ou complexidade.','Entender comportamento é essencial para desenhar serviços que as pessoas realmente adotem.']);
  add('deijanete-fayad-seguranca','deijanete-fayad','EXPERIÊNCIA','Segurança percebida muda a forma como as pessoas usam um serviço','Iluminação, informação, atendimento e previsibilidade influenciam confiança.',IMG.bikes,['Experiência de mobilidade começa antes do veículo.','Ambiente, comunicação e facilidade de pedir ajuda influenciam sensação de controle.','Serviços bem desenhados reduzem ansiedade e tornam a jornada mais previsível.']);
  add('deijanete-fayad-marcas','deijanete-fayad','COMUNICAÇÃO','Tecnologia precisa ser explicada em linguagem humana','Marcas ganham confiança quando mostram benefício antes da sigla.',IMG.tecnologia,['Excesso de termos técnicos pode afastar o consumidor.','Uma boa comunicação explica o que muda no cotidiano e quais são os limites do recurso.','Clareza ajuda a construir confiança e decisão mais consciente.']);

  const themes={
    automoveis:{title:'Automóveis',tag:'LANÇAMENTOS • TEST-DRIVE • MERCADO',lead:'Do carro urbano aos modelos premium, notícias e análises sobre produto, segurança, consumo e mercado.',hero:IMG.carros,articles:['lancamento-jeep-avenger-2026','automoveis-mercado','automoveis-seguranca','automoveis-test-drive']},
    motos:{title:'Motos',tag:'DUAS RODAS • CIDADE • ESTRADA',lead:'Mercado, tecnologia, segurança e experiência para quem se move em duas rodas.',hero:IMG.motos,articles:['motos-mercado','motos-seguranca','motos-estrada']},
    bikes:{title:'Bikes e E-bikes',tag:'URBANO • ESPORTE • E-MOBILITY',lead:'Bicicletas, e-bikes, infraestrutura urbana e cicloturismo.',hero:IMG.bikes,articles:['bikes-cidade','bikes-eletricas','bikes-turismo']},
    eletricos:{title:'Elétricos e Híbridos',tag:'ENERGIA • BATERIAS • RECARGA',lead:'Eletrificação explicada pelo uso real: tecnologia, recarga e custo total.',hero:IMG.eletricos,articles:['eletricos-mercado','eletricos-recarga','eletricos-custo']},
    locadoras:{title:'Locadoras e Frotas',tag:'ALUGUEL • ASSINATURA • EMPRESAS',lead:'Locação, frotas corporativas e assinatura no Brasil e no exterior.',hero:IMG.locadoras,articles:['locadoras-redes','locadoras-aeroportos','locadoras-assinatura']},
    concessionarias:{title:'Concessionárias',tag:'VAREJO • PÓS-VENDA • EXPERIÊNCIA',lead:'Showroom, jornada digital, test-drive, oficina e relacionamento.',hero:IMG.concessionarias,articles:['concessionarias-digital','concessionarias-posvenda','concessionarias-experiencia']},
    nautica:{title:'Náutica',tag:'EMBARCAÇÕES • MARINAS • TURISMO',lead:'Mercado náutico, infraestrutura, tecnologia e experiências sobre a água.',hero:IMG.nautica,articles:['nautica-mercado','nautica-marinas','nautica-tecnologia']},
    aviacao:{title:'Aviação',tag:'COMPANHIAS • TÁXI AÉREO • AEROPORTOS',lead:'Da aviação regular à executiva: companhias, táxi aéreo, aeroportos e operações especializadas.',hero:IMG.aviacao,articles:['aviacao-companhias','aviacao-taxi-aereo','aviacao-aeroportos','aviacao-executiva']},
    tecnologia:{title:'Tecnologia da Mobilidade',tag:'IA • DADOS • CONECTIVIDADE',lead:'Software, sensores, inteligência artificial e serviços digitais mudando a experiência de deslocamento.',hero:IMG.tecnologia,articles:['tecnologia-conectada','tecnologia-ia','tecnologia-pagamentos']},
    lancamentos:{title:'Lançamentos',tag:'ÚLTIMAS NOVIDADES • DESIGN • DESEMPENHO',lead:'O que acabou de chegar ao mercado e o que realmente mudou para o consumidor.',hero:IMG.carros,articles:['lancamento-jeep-avenger-2026','lancamentos-agenda','lancamentos-analise']},
    carros:{title:'Automóveis em destaque',tag:'CARROS • PERFORMANCE • MERCADO',lead:'Guias e análises para entender escolha, desempenho e tecnologia.',hero:IMG.carros,articles:['carros-escolha','carros-performance','carros-tecnologia']},
    'test-drive':{title:'Teste & Experiência Voz',tag:'AVALIAÇÃO • USO REAL • OPINIÃO',lead:'Avaliações estruturadas para mostrar como o veículo se comporta fora da ficha técnica.',hero:IMG.carros,articles:['test-drive-metodo','test-drive-cidade','test-drive-estrada']},
    entrevistas:{title:'Entrevistas do Setor',tag:'EXECUTIVOS • ESPECIALISTAS • LIDERANÇAS',lead:'Conversas que explicam estratégia, inovação, investimento e futuro da mobilidade.',hero:IMG.entrevista,articles:['entrevistas-executivos','entrevistas-especialistas','entrevistas-futuro']},
    'paulo-fayad':{title:'Paulo Fayad',tag:'COMENTÁRIO VOZ • MOBILIDADE',lead:'Jornalismo e leitura de mercado aplicados à indústria, infraestrutura e comportamento.',hero:IMG.carros,articles:['paulo-fayad-analise','paulo-fayad-mercado','paulo-fayad-infra']},
    'deijanete-fayad':{title:'Deijanete Fayad',tag:'COMENTÁRIO VOZ • EXPERIÊNCIA',lead:'Comportamento, percepção de segurança e comunicação no universo da mobilidade.',hero:IMG.tecnologia,articles:['deijanete-fayad-comportamento','deijanete-fayad-seguranca','deijanete-fayad-marcas']}
  };
  window.VOZ_MOBILIDADE={themes,articles};
})();
