const FEEDS=[
  ['Brasil','https://news.google.com/rss/search?q=Brasil+not%C3%ADcias+hoje&hl=pt-BR&gl=BR&ceid=BR:pt-419'],
  ['Brasília','https://news.google.com/rss/search?q=Bras%C3%ADlia+DF+not%C3%ADcias+hoje&hl=pt-BR&gl=BR&ceid=BR:pt-419'],
  ['Política','https://news.google.com/rss/search?q=pol%C3%ADtica+Brasil+elei%C3%A7%C3%B5es+2026&hl=pt-BR&gl=BR&ceid=BR:pt-419'],
  ['Economia','https://news.google.com/rss/search?q=economia+Brasil+hoje&hl=pt-BR&gl=BR&ceid=BR:pt-419'],
  ['Mundo','https://news.google.com/rss/search?q=mundo+internacional+not%C3%ADcias+hoje&hl=pt-BR&gl=BR&ceid=BR:pt-419'],
  ['Goiás','https://news.google.com/rss/search?q=Goi%C3%A1s+Goi%C3%A2nia+not%C3%ADcias+hoje&hl=pt-BR&gl=BR&ceid=BR:pt-419']
];
function decode(str=''){return String(str).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
function cleanTitle(title=''){return decode(title).replace(/\s+-\s+[^-]{2,90}$/,'').replace(/\s+/g,' ').trim();}
function extract(xml,topic){const out=[];const blocks=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];for(const block of blocks.slice(0,18)){const title=cleanTitle((block.match(/<title>([\s\S]*?)<\/title>/i)||[])[1]||'');const link=decode((block.match(/<link>([\s\S]*?)<\/link>/i)||[])[1]||'').trim();const pubDate=decode((block.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)||[])[1]||'').trim();if(title&&link)out.push({title,link,pubDate,topic});}return out;}
function score(item){let s=0;const d=Date.parse(item.pubDate);if(Number.isFinite(d)){const age=(Date.now()-d)/3600000;s+=Math.max(0,36-age);}if(item.topic==='Brasília')s+=4;if(item.topic==='Brasil')s+=3;if(item.topic==='Política')s+=2;return s;}
module.exports=async function handler(req,res){try{const batches=await Promise.all(FEEDS.map(async([topic,url])=>{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 VOZ NEWS'}});if(!r.ok)return[];return extract(await r.text(),topic);}));const seen=new Set();const headlines=batches.flat().filter(x=>{const d=Date.parse(x.pubDate);return !Number.isFinite(d)||(Date.now()-d)<48*3600000;}).sort((a,b)=>score(b)-score(a)).filter(x=>{const k=x.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).slice(0,24);if(!headlines.length)throw new Error('feed vazio');res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=120');return res.status(200).json({updatedAt:new Date().toISOString(),headlines});}catch(e){return res.status(500).json({error:'Não foi possível atualizar as manchetes agora.'});}};