const people = [
  {name:'Lula', handle:'lulaoficial', role:'Presidência da República', title:'Lula abre oficialmente a campanha de 2026 com agenda nacional e foco em propostas para o país', link:'https://noticias.uol.com.br/eleicoes/2026/08/16/eleicoes-lula-flavio-bolsonaro-inicio-da-campanha.ghtm', source:'Campanha 2026'},
  {name:'Celina Leão', handle:'celinaleao', role:'Governo do Distrito Federal', title:'Celina Leão abre campanha de reeleição ao Governo do DF ao lado de apoiadores em Ceilândia', link:'https://celina11.com/noticias/celina-leao-abre-campanha-de-reeleicao-ao-governo-do-df-ao-lado-de-michelle-bolsonaro-e-bia-kicis/', source:'Campanha oficial 2026'},
  {name:'Julio Cesar Ribeiro', handle:'juliocesarribeiro', role:'Câmara dos Deputados • DF', title:'Julio Cesar Ribeiro mantém agenda de trabalho e propostas voltadas ao esporte, proteção social e desenvolvimento do DF', link:'https://www.camara.leg.br/deputados/204372', source:'Câmara dos Deputados'},
  {name:'Gilberto Nascimento', handle:'gnascimento_20', role:'Câmara dos Deputados • SP', title:'Gilberto Nascimento amplia atuação parlamentar em educação, direitos humanos, energia e defesa das famílias', link:'https://www.camara.leg.br/deputados/74270', source:'Câmara dos Deputados'},
  {name:'Hermeto', handle:'hermeto.oficial', role:'Câmara Legislativa • DF', title:'Pesquisa espontânea coloca Hermeto entre os 10 mais lembrados do DF e reforça reconhecimento nas comunidades', link:'https://hermeto.com.br/', source:'Site oficial • notícia recente'},
  {name:'Paula Belmonte', handle:'paulabelmonteoficial', role:'Câmara Legislativa • DF', title:'PSDB-DF confirma Paula Belmonte como candidata ao Governo do DF e apresenta prioridades para Brasília', link:'https://paulabelmonte.com.br/psdb-df-confirma-paula-belmonte-como-candidata-ao-gdf-em-convencao-no-dia-4-de-agosto/', source:'Campanha oficial 2026'}
];

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

export default async function handler(req,res){
  const now=new Date();
  const date=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'long',year:'numeric'}).format(now);
  const cards=people.map(p=>`<article class="card"><a class="photo" href="https://www.instagram.com/${esc(p.handle)}/" target="_blank" rel="noopener"><img src="/api/instagram-photo?handle=${encodeURIComponent(p.handle)}&v=3" alt="${esc(p.name)}" loading="eager" onerror="this.onerror=null;this.src='/logo-voznews-oficial.png'"></a><div class="body"><span>${esc(p.role)}</span><h2>${esc(p.name)}</h2><h3>${esc(p.title)}</h3><p>${esc(p.source)} • cobertura positiva da campanha e atuação pública.</p><div class="actions"><a href="${esc(p.link)}" target="_blank" rel="noopener">Ler notícia →</a><a href="https://www.instagram.com/${esc(p.handle)}/" target="_blank" rel="noopener">@${esc(p.handle)}</a></div></div></article>`).join('');
  res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.status(200).send(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quem Decide o Brasil | VOZ NEWS</title><meta name="description" content="Cobertura política positiva e de campanha do VOZ NEWS."><style>:root{--g:#d4af37;--b:#061423;--w:#fff;--m:#d5e2ef}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:linear-gradient(145deg,#04101d,#0a2742 58%,#07111c);color:var(--w)}header{position:sticky;top:0;z-index:3;background:#061423ee;border-bottom:1px solid #d4af3744}.bar{width:min(1200px,92%);height:92px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:18px}.logo{width:230px;max-width:54vw}.back{color:white;text-decoration:none;border:1px solid #d4af3766;padding:12px 18px;border-radius:999px;font-weight:800}main{width:min(1200px,92%);margin:auto;padding:58px 0 80px}.kicker{color:var(--g);font-weight:900;letter-spacing:1.5px}.hero h1{font-size:clamp(36px,6vw,70px);margin:10px 0}.hero p{font-size:19px;line-height:1.55;color:var(--m);max-width:850px}.updated{margin:20px 0 30px;color:#fff;font-weight:800}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.card{overflow:hidden;border:1px solid #d4af3744;border-radius:24px;background:#ffffff0c;box-shadow:0 18px 50px #0005}.photo{display:block;height:320px;background:#0a1f35}.photo img{width:100%;height:100%;object-fit:cover;object-position:center top}.body{padding:20px}.body>span{display:inline-block;color:var(--g);font-size:12px;font-weight:900;text-transform:uppercase}.body h2{font-size:28px;margin:7px 0}.body h3{font-size:18px;line-height:1.3;margin:8px 0 12px}.body p{color:var(--m);line-height:1.45}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.actions a{padding:10px 13px;border-radius:999px;background:#d4af37;color:#061423;text-decoration:none;font-weight:900;font-size:13px}.actions a+a{background:#ffffff12;color:#fff;border:1px solid #ffffff25}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.bar{height:76px}.back{font-size:12px;padding:9px 11px}.grid{grid-template-columns:1fr}.photo{height:360px}main{padding-top:38px}}</style></head><body><header><div class="bar"><a href="/"><img class="logo" src="/logo-voznews-oficial.png" alt="VOZ NEWS"></a><a class="back" href="/#politica">← Voltar ao VOZ NEWS</a></div></header><main><section class="hero"><div class="kicker">QUEM DECIDE O BRASIL • CAMPANHA 2026</div><h1>Política com foco em propostas e realizações.</h1><p>Cobertura editorial positiva das campanhas e da atuação pública de Lula, Celina Leão, Julio Cesar Ribeiro, Gilberto Nascimento, Hermeto e Paula Belmonte.</p><div class="updated">Atualizado em ${esc(date)}</div></section><section class="grid">${cards}</section></main></body></html>`);
}
